### ISSUE TITLE
"WEBSCREENSHOT=true" hangs with reconftw_axiom.sh

### ISSUE THREAD

**Issue by itsgudenuf** [six2dez/reconftw#250] opened 2021-04-30 23:19 UTC
**Describe the bug**
Every time time I run the ./reconftw_axiom.sh -d SomeDomain.Tld -r

one random node will hang during the gowitness scan
line 671
axiom-scan .tmp/webs_screenshots.txt -m gowitness -o screenshots 

**To Reproduce**
1. spin up a 5 node (or larger) Axiom fleet. 
   I'm using the g6-standard-2 at Linode
2. ./reconftw_axiom.sh -d paypal.com -r
3. wait for the  "Web Screenshots"
4. watch the tmp logs see when each node finishes with it's list.  One node always seems to hang

To get things moving again, I axiom-ssh into the stuck node and perform a "pkill -9 chrome"  and recon continues 

**Expected behavior**
scan should complete (or time out)

**Screenshots**

**Desktop (please complete the following information):**
- Linode g6-standard-2
- ReconFTW Image
- updated ReconFTW & axiom this morning (04/30/21 08:00 CDT)

**Additional context**
The amount of data this recon script collects is Overwhelming. 
This is some fantastic work!  Bravo and Thank You.

**Comment by six2dez** [comment] 2021-05-01 16:08
Seems to be a gowitness issue, I'm looking for a good replacement, for the moment my bet is [webscreenshot](https://github.com/maaaaz/webscreenshot) . It doesn't have html report but works really good.

**Comment by itsgudenuf** [comment] 2021-05-01 16:18
Thanks @six2dez , I'll check it out. It shouldn't be too hard to deploy to Axiom. And maybe we can get it added to the next ReconFTW image.

This morning I worked on the function fuzz() in reconftw_axiom.sh and got it to use axiom-scan instead.
With the old function it took 3+ hours to fuzz the 228 domains in my paypal.com webs.txt.
After the rewritten function...
11 minutes on a 6 node cluster of 2 vcpu linodes. 
Once I finish testing I'll do a PR.

**Comment by 0-0eth0** [comment] 2021-05-01 16:25
Hey @itsgudenuf 
Feel free to do PR :) Contributions will be always appreciated.

Cheers,
0_0eth0

**Comment by six2dez** [comment] 2021-05-01 16:32
About webscreenshot is already done [here](https://github.com/pry0cc/axiom/pull/317/commits/5fafa12bd58cb82c725cdaf4ae1ec91c4cbc76d4) but not merged in axiom master :/. I'm testing it again right now.

**Comment by gprime31** [comment] 2021-05-02 19:29
Aquatone is still my go-to for screen shots :)

**Comment by gprime31** [comment] 2021-05-02 21:23
The Creator of axiom was on nahamsec's stream and gowitness hung on him also, he said it's on the to-do list,
So it's not a bug with reconftw or gowitness, it's a bug in axiom.

**Comment by itsgudenuf** [comment] 2021-05-02 21:29
Thanks @gprime31 , now that you mention that, I do remember him saying something about that.
I think a simple timeout option could solve the issue.
I'll make up a gowitness-to.json module and test it out.

I noticed there was already an aquatone module in Axiom too.

Maybe we can adjust reconftw_axiom to use whichever one we like with a switch or two in the cfg file.  I'll look at that... after I get all the other PRs I need to do.

**Comment by six2dez** [comment] 2021-05-02 23:44
I've tested axiom's aquatone module, and it works almost good, it generates one html report per instance which is not perfect :/

For me there are 3 options:
 - use maaaz/webscreenshot without html report
 - fix gowitness
 - try any other alternative like eyewitness, but this would require creating a new axiom module and modify reconftw installer and axiom provider

**Comment by itsgudenuf** [comment] 2021-05-02 23:57
for now...
How about adding a function for aquatone now and defaulting it to false in the cfg.  Then the user can select between aquatone or gowitness

I'm working on the order of things, especially in the multi_recon so I can just spin up the fleet when I need it and shut it down when I'm done. 

I'm also adding some timeout commands in spots where I've seen it hang.  And making a few timeout variables configurable in the cfg.

Quick formatting ?
For if statements,  do you like 
```
if [ test ]; then
   ...
fi
```
-- OR -- 
```
if [ test ]
then
  ...
fi
```

**Comment by six2dez** [comment] 2021-05-03 00:03
Ok, we can add the function for aquatone, no problem, just a bit busy next 2-3 days.

About formatting I prefer:

```
if [ test ]; then
   ...
fi
```

but my code editor always put "then" in the next line, so.... an entire code reformat is required for this change XD

**Comment by itsgudenuf** [comment] 2021-05-03 00:14
RE: formatting  I write my stuff the way you prefer. That's my preference too.  I'll correct the stuff I touch.

Totally understand busy :)

**Comment by six2dez** [comment] 2021-05-06 10:39
Fixed in dev https://github.com/six2dez/reconftw/commit/5f75750d14334042154dfd0eaadc74b31988fd13

**Closed by six2dez** 2021-05-06 10:39 UTC
Labels: bug
