### ISSUE TITLE
Js scraping and js file analysis 

### ISSUE THREAD

**Issue by nirajdhalani** [six2dez/reconftw#84] opened 2021-01-27 04:18 UTC
Js scraping option in subdomain 4/6 and js file analysis take too time consuming it takes 1 day for only js scraping and other 1 and half day take js file analysis

**Comment by detonxx** [comment] 2021-01-27 05:33
The issue was with the **SubDomainizer** tool which now has been removed and in its place **JSFinder** is implemented.
Please git clone again the latest repo and report if you are facing the same issues.

**Comment by nirajdhalani** [comment] 2021-01-27 06:13
I am talking about latest version

**Comment by nirajdhalani** [comment] 2021-01-27 06:14
I tried 2-3 times but it takes 1 or 2 days for only one module js scraping

**Comment by six2dez** [comment] 2021-01-27 07:50
We can't reproduce the issue, please provide more details, screenshots or try to run in verbose mode with `-v` flag. 
Otherwise we can only close this issue :/

**Comment by bileltechno** [comment] 2021-01-27 09:10
> I am talking about latest version 

Last version and fixs are in the dev branche.

2 days is too much. Are your connection is good enough!

Is  your target Google.com or Facebook?

**Comment by nirajdhalani** [comment] 2021-01-27 09:35
yes i am using vps

**Comment by six2dez** [comment] 2021-01-27 10:35
Every fix is on main now, please @nirajdhalani make a new test, if it fails again, please provide more information in order to solve this issue.

**Comment by six2dez** [comment] 2021-01-29 08:15
No answer, closing

**Closed by six2dez** 2021-01-29 08:15 UTC
Labels: help wanted
